name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    name: dual-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Publish to Github and npmjs
        uses: pascalgn/npm-publish-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.npm_token }}
